/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author victor.fernandez
 */
public class CalculadoraJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraJFrame
     */
    public CalculadoraJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDisplay = new javax.swing.JTextField();
        MemoriaBorrar = new javax.swing.JButton();
        jButtonMemoriaRecuperar = new javax.swing.JButton();
        jButtonMemoriaSumar = new javax.swing.JButton();
        jButtonN7 = new javax.swing.JButton();
        jButtonN8 = new javax.swing.JButton();
        jButtonN9 = new javax.swing.JButton();
        jButtonN4 = new javax.swing.JButton();
        jButtonN5 = new javax.swing.JButton();
        jButtonN6 = new javax.swing.JButton();
        jButtonMemoriaRestar = new javax.swing.JButton();
        jButtonDividir = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButtonRestar = new javax.swing.JButton();
        jButtonN1 = new javax.swing.JButton();
        jButtonN2 = new javax.swing.JButton();
        jButtonN3 = new javax.swing.JButton();
        jButtonPunto = new javax.swing.JButton();
        jButtonN0 = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonSumar = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);

        jTextFieldDisplay.setEditable(false);
        jTextFieldDisplay.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldDisplay.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.setText("2342.089");

        MemoriaBorrar.setBackground(new java.awt.Color(102, 102, 255));
        MemoriaBorrar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MemoriaBorrar.setText("MC");
        MemoriaBorrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MemoriaBorrar.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonMemoriaRecuperar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonMemoriaRecuperar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonMemoriaRecuperar.setText("MR");
        jButtonMemoriaRecuperar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonMemoriaRecuperar.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonMemoriaSumar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonMemoriaSumar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonMemoriaSumar.setText("M+");
        jButtonMemoriaSumar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonMemoriaSumar.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonMemoriaSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemoriaSumarActionPerformed(evt);
            }
        });

        jButtonN7.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN7.setText("7");
        jButtonN7.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN8.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN8.setText("8");
        jButtonN8.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN9.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN9.setText("9");
        jButtonN9.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN4.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN4.setText("4");
        jButtonN4.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN5.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN5.setText("5");
        jButtonN5.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN6.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN6.setText("6");
        jButtonN6.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonMemoriaRestar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonMemoriaRestar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonMemoriaRestar.setText("M-");
        jButtonMemoriaRestar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonMemoriaRestar.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonDividir.setBackground(new java.awt.Color(255, 153, 153));
        jButtonDividir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonDividir.setText("/");
        jButtonDividir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonDividir.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonMultiplicar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonMultiplicar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonMultiplicar.setText("*");
        jButtonMultiplicar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonMultiplicar.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonRestar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonRestar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonRestar.setText("-");
        jButtonRestar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonRestar.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN1.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN1.setText("1");
        jButtonN1.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN2.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN2.setText("2");
        jButtonN2.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN3.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN3.setText("3");
        jButtonN3.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonPunto.setBackground(new java.awt.Color(153, 153, 153));
        jButtonPunto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonPunto.setText(".");
        jButtonPunto.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonN0.setBackground(new java.awt.Color(153, 153, 153));
        jButtonN0.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonN0.setText("0");
        jButtonN0.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN0ActionPerformed(evt);
            }
        });

        jButtonIgual.setBackground(new java.awt.Color(0, 204, 102));
        jButtonIgual.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonIgual.setText("=");
        jButtonIgual.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonIgual.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButtonSumar.setBackground(new java.awt.Color(255, 153, 153));
        jButtonSumar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonSumar.setText("+");
        jButtonSumar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonSumar.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonBack.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jButtonBack.setText(" ←");
        jButtonBack.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonBack.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonRaiz.setBackground(new java.awt.Color(255, 153, 153));
        jButtonRaiz.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonRaiz.setText("√");
        jButtonRaiz.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonRaiz.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonC.setText("C");
        jButtonC.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonC.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MemoriaBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMemoriaRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMemoriaSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonN7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonN4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMemoriaRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonN1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonN2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonN3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonN0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDisplay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MemoriaBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMemoriaRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMemoriaSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonN7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonN8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonN9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonN4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonN5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonN6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonN1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonN2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonN3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonN0, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMemoriaRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButtonMemoriaSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemoriaSumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMemoriaSumarActionPerformed

    private void jButtonN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN0ActionPerformed
        annadirCifra('0');
    }//GEN-LAST:event_jButtonN0ActionPerformed

    public void annadirCifra(char cifra) {
        
    }
    
    public double obtenerCifraDisplay() {
        return Double.parseDouble(jTextFieldDisplay.getText());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */ 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MemoriaBorrar;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMemoriaRecuperar;
    private javax.swing.JButton jButtonMemoriaRestar;
    private javax.swing.JButton jButtonMemoriaSumar;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonN0;
    private javax.swing.JButton jButtonN1;
    private javax.swing.JButton jButtonN2;
    private javax.swing.JButton jButtonN3;
    private javax.swing.JButton jButtonN4;
    private javax.swing.JButton jButtonN5;
    private javax.swing.JButton jButtonN6;
    private javax.swing.JButton jButtonN7;
    private javax.swing.JButton jButtonN8;
    private javax.swing.JButton jButtonN9;
    private javax.swing.JButton jButtonPunto;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonRestar;
    private javax.swing.JButton jButtonSumar;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
